name: Cache
on: 
  pull_request:
  push:
    branches:
      - main
      - v0.6.x
  merge_group:

permissions: read-all

jobs:
    Cache:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/cache@v3 
          with: 
            path: | 
              ~/.cargo/ 
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
